---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: xray
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~4.0
    flux.weave.works/locked: 'true'
    flux.weave.works/locked_msg: '"Halt updates for now"'
    flux.weave.works/locked_user: Stefan Prodan <stefan@weave.works>
spec:
  releaseName: xray
  chart:
    repository: https://github.com/jfrog
    path: charts/tree/master/stable/xray
    name: xray
    version: 5.1.3
